spring.application.name=ViajouSpring

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

# Define o caminho para o endpoint da documentação da API
springdoc.api-docs.path=/v3/api-docs

# Define o caminho para a interface do Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
